package com.rest_jpa.exceptions;

public enum ErrorKey {
    PERSONS_NOT_FOUND,
    PERSON_NOT_FOUND,
    PERSON_NOT_CREATED,
    PERSON_NOT_UPDATED,

    ITEMS_NOT_FOUND,
    ITEM_NOT_FOUND,
    ITEM_NOT_CREATED,
    ITEM_NOT_UPDATED,

    TASKS_NOT_FOUND,
    TASK_NOT_FOUND,
    TASK_NOT_CREATED,
    TASK_NOT_UPDATED,

    CUSTOMER_ORDERS_NOT_FOUND,
    CUSTOMER_ORDER_NOT_FOUND,
    CUSTOMER_ORDER_NOT_CREATED,
    CUSTOMER_ORDER_NOT_UPDATED
}
