package com.rest_jpa.exceptions;

public enum ErrorKey {
    USERS_NOT_FOUND,
    USER_NOT_FOUND,
    USER_NOT_CREATED,
    USER_NOT_UPDATED,

    ITEMS_NOT_FOUND,
    ITEM_NOT_FOUND,
    ITEM_NOT_CREATED,
    ITEM_NOT_UPDATED,
    ITEM_PRESENT_IN_SOME_CUSTOMER_ORDERS,

    TASKS_NOT_FOUND,
    TASK_NOT_FOUND,
    TASK_NOT_CREATED,
    TASK_NOT_UPDATED,

    CUSTOMER_ORDERS_NOT_FOUND,
    CUSTOMER_ORDER_NOT_FOUND,
    CUSTOMER_ORDER_NOT_CREATED,
    CUSTOMER_ORDER_NOT_UPDATED,

    WRONG_INPUT_DATA
}
