DROP TABLE order_furniture IF EXISTS;
DROP TABLE person IF EXISTS;
DROP TABLE department IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE department (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          VARCHAR(50)         NOT NULL
);

CREATE TABLE person (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          VARCHAR(50)         NOT NULL,
  department_id INTEGER              NOT NULL,
  middle_name   VARCHAR(50)         DEFAULT NULL,
  sur_name      VARCHAR(50)         NOT NULL
);
ALTER TABLE person ADD CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES department (id)
ON DELETE CASCADE;

CREATE TABLE order_furniture (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name          VARCHAR(50)         NOT NULL,
  date          TIMESTAMP            DEFAULT now(),
  is_assigned   BOOLEAN              DEFAULT FALSE,
  employee_id   INTEGER              DEFAULT NULL,
  department_id INTEGER              NOT NULL
);
ALTER TABLE order_furniture ADD CONSTRAINT fk_order_furniture_employee FOREIGN KEY (employee_id) REFERENCES person (id);
ALTER TABLE order_furniture ADD CONSTRAINT fk_order_furniture_department FOREIGN KEY (department_id) REFERENCES department (id)
ON DELETE CASCADE;
